import json
import os

ui_ts_path = 'src/i18n/ui.ts'

with open(ui_ts_path, 'r') as f:
    text = f.read()

keys_to_remove = [
  "about.meta.title", "about.meta.desc", "about.title", "about.intro", 
  "about.vision.title", "about.vision.p1", "about.vision.p2", 
  "about.offer.title", "about.offer.l1.title", "about.offer.l1", 
  "about.offer.l2.title", "about.offer.l2", "about.offer.l3.title", 
  "about.offer.l3", "about.promise.title", "about.promise.p1", "about.quote",
  "terms.meta.title", "terms.meta.desc", "terms.intro", 
  "terms.s1.p1", "terms.s2.title", "terms.s2.p1", "terms.s2.l1", "terms.s2.l2", 
  "terms.s3.p1", "terms.s3.l1", "terms.s3.l2", "terms.s4.title", "terms.s4.p1", 
  "terms.s4.l1", "terms.s4.l2", "terms.s4.l3", "terms.s5.title", "terms.s5.p1", 
  "terms.s6.title", "terms.s6.p1"
]

lines = text.split('\n')
new_lines = []
for line in lines:
    skip = False
    for k in keys_to_remove:
        if f"'{k}':" in line or f'"{k}":' in line:
            skip = True
            break
    if not skip:
        new_lines.append(line)

text = '\n'.join(new_lines)

translations = {
  "zh-TW": {
    "about": {
      "about.meta.title": "關於我們 About Us | Barista Flow",
      "about.meta.desc": "了解 Barista Flow 的創立宗旨。我們致力於將咖啡科學數據化，打造全球最專業的精品咖啡沖煮工具。",
      "about.title": "關於我們",
      "about.intro": "在精品咖啡的世界裡，細微的變數決定了最終的風味。Barista Flow 的誕生，是為了解決一個所有咖啡愛好者都會遇到的問題：「如何讓每一次的沖煮都穩定、精確，且充滿科學根據？」",
      "about.vision.title": "我們的願景",
      "about.vision.p1": "我們是一群對咖啡充滿熱忱的開發者與咖啡師。我們相信，一杯好咖啡不應該只靠「感覺」或「運氣」。水溫、粉水比、研磨度，以及至關重要的流體力學（注水節奏），都是可以用科學數據來量化與控制的。",
      "about.vision.p2": "是建立一個全球最專業且易於使用的咖啡沖煮工具平台，讓無論是剛接觸手沖的新手，還是身經百戰的職業咖啡師，都能在這裡找到提升萃取品質的解答。",
      "about.offer.title": "我們提供什麼？",
      "about.offer.l1.title": "互動式三階段計時器",
      "about.offer.l1": "根據您的豆種與水粉比，即時運算出悶蒸、主萃取與尾段的最佳注水時機與水量目標。",
      "about.offer.l2.title": "參數儲存與分享",
      "about.offer.l2": "讓您能夠儲存每一次成功的配方，並透過專屬網址與全世界的咖啡同好分享您的沖煮哲學。",
      "about.offer.l3.title": "深度科學知識庫",
      "about.offer.l3": "我們不寫空洞的文章。我們的知識庫深入探討流體力學、梅納反應與萃取率的物理限制，幫助您知其然，更知其所以然。",
      "about.promise.title": "我們的承諾",
      "about.promise.p1": "Barista Flow 承諾始終保持核心工具的免費使用。我們致力於提供極致的無干擾使用者體驗（包含精心設計的深色模式與平滑的動畫），因為我們知道，在專注沖煮咖啡的那三分鐘裡，您不應該被任何糟糕的介面所打擾。",
      "about.quote": "精準，是萃取極致風味的唯一途徑。",
    },
    "terms": {
      "terms.meta.title": "服務條款 | Barista Flow",
      "terms.meta.desc": "Barista Flow 的服務條款。規範本網站的使用條例、智慧財產權與免責聲明。",
      "terms.intro": "歡迎您使用 Barista Flow（以下簡稱「本網站」）。當您瀏覽、存取或使用本網站提供的任何工具與內容時，即表示您完全同意並接受以下服務條款。如果您不同意本條款的任何部分，請勿使用本網站。",
      "terms.s1.p1": "Barista Flow 提供免費的線上咖啡沖煮計時器、參數計算工具，以及咖啡科學相關的知識文章。本網站旨在提供個人、非商業用途的參考與協助。",
      "terms.s2.title": "智慧財產權聲明",
      "terms.s2.p1": "本網站的所有內容，包含但不限於文字、標誌、圖片、圖表、應用程式碼、UI 設計及架構，其著作權、商標權及其他智慧財產權皆屬於 Barista Flow 團隊所有，或已取得合法授權。",
      "terms.s2.l1": "未經我們事先的書面許可，您不得對本網站內容進行複製、修改、散佈、出版、展示或用於任何商業行為。",
      "terms.s2.l2": "您可以為了個人學習目的分享本網站的連結（例如使用我們的「分享此配方」功能）。",
      "terms.s3.p1": "本網站提供的所有咖啡參數、教學文章與計時工具皆「按原樣」提供。雖然我們力求資訊的科學性與準確性，但咖啡沖煮受到諸多實體變數（如水質、豆種、氣溫等）影響。",
      "terms.s3.l1": "我們對本網站內容的絕對準確性、完整性或適用性不作任何明示或暗示的保證。",
      "terms.s3.l2": "對於因使用本網站工具或依賴本網站資訊而造成的任何直接、間接或附帶損失（包括但不限於咖啡豆的損耗或設備的損壞），Barista Flow 概不負責。",
      "terms.s4.title": "使用者行為規範",
      "terms.s4.p1": "在使用本網站時，您同意遵守所有適用的法律法規，並且不得：",
      "terms.s4.l1": "以任何可能導致本網站伺服器或網路負載過重、受損或中斷的方式使用本網站（例如進行 DDoS 攻擊或惡意爬蟲擷取）。",
      "terms.s4.l2": "試圖未經授權存取本網站的後台系統或原始碼。",
      "terms.s4.l3": "利用本網站從事任何違法或欺詐行為。",
      "terms.s5.title": "第三方服務與廣告",
      "terms.s5.p1": "本網站可能包含第三方網站的連結或展示第三方廣告（如 Google AdSense）。我們無法控制這些第三方網站的內容與隱私政策。點擊廣告或外部連結產生的任何風險，由使用者自行承擔。",
      "terms.s6.title": "條款的修改與終止",
      "terms.s6.p1": "我們保留隨時修改、暫停或終止本網站服務及本服務條款的權利，恕不另行通知。您繼續使用本網站即表示您接受任何修改後的條款。",
    }
  },
  "zh-CN": {
    "about": {
      "about.meta.title": "关于我们 About Us | Barista Flow",
      "about.meta.desc": "了解 Barista Flow 的创立宗旨。我们致力于将咖啡科学数据化，打造全球最专业的精品咖啡冲煮工具。",
      "about.title": "关于我们",
      "about.intro": "在精品咖啡的世界里，细微的变数决定了最终的风味。Barista Flow 的诞生，是为了解决一个所有咖啡爱好者都会遇到的问题：“如何让每一次的冲煮都稳定、精确，且充满科学根据？”",
      "about.vision.title": "我们的愿景",
      "about.vision.p1": "我们是一群对咖啡充满热忱的开发者与咖啡师。我们相信，一杯好咖啡不应该只靠“感觉”或“运气”。水温、粉水比、研磨度，以及至关重要的流体力学（注水节奏），都是可以用科学数据来量化与控制的。",
      "about.vision.p2": "是建立一个全球最专业且易于使用的咖啡冲煮工具平台，让无论是刚接触手冲的新手，还是身经百战的职业咖啡师，都能在这里找到提升萃取品质的解答。",
      "about.offer.title": "我们提供什么？",
      "about.offer.l1.title": "互动式三阶段计时器",
      "about.offer.l1": "根据您的豆种与水粉比，即时运算出闷蒸、主萃取与尾段的最佳注水时机与水量目标。",
      "about.offer.l2.title": "参数储存与分享",
      "about.offer.l2": "让您能够储存每一次成功的配方，并透过专属网址与全世界的咖啡同好分享您的冲煮哲学。",
      "about.offer.l3.title": "深度科学知识库",
      "about.offer.l3": "我们不写空洞的文章。我们的知识库深入探讨流体力学、梅纳反应与萃取率的物理限制，帮助您知其然，更知其所以然。",
      "about.promise.title": "我们的承诺",
      "about.promise.p1": "Barista Flow 承诺始终保持核心工具的免费使用。我们致力于提供极致的无干扰使用者体验（包含精心设计的深色模式与平滑的动画），因为我们知道，在专注冲煮咖啡的那三分钟里，您不应该被任何糟糕的界面所打扰。",
      "about.quote": "精准，是萃取极致风味的唯一途径。",
    },
    "terms": {
      "terms.meta.title": "服务条款 | Barista Flow",
      "terms.meta.desc": "Barista Flow 的服务条款。规范本网站的使用条例、知识产权与免责声明。",
      "terms.intro": "欢迎您使用 Barista Flow（以下简称“本网站”）。当您浏览、访问或使用本网站提供的任何工具与内容时，即表示您完全同意并接受以下服务条款。如果您不同意本条款的任何部分，请勿使用本网站。",
      "terms.s1.p1": "Barista Flow 提供免费的线上咖啡冲煮计时器、参数计算工具，以及咖啡科学相关的知识文章。本网站旨在提供个人、非商业用途的参考与协助。",
      "terms.s2.title": "知识产权声明",
      "terms.s2.p1": "本网站的所有内容，包含但不限于文字、标志、图片、图表、应用程序代码、UI 设计及架构，其著作权、商标权及其他知识产权皆属于 Barista Flow 团队所有，或已取得合法授权。",
      "terms.s2.l1": "未经我们事先的书面许可，您不得对本网站内容进行复制、修改、分发、出版、展示或用于任何商业行为。",
      "terms.s2.l2": "您可以为了个人学习目的分享本网站的链接（例如使用我们的“分享此配方”功能）。",
      "terms.s3.p1": "本网站提供的所有咖啡参数、教学文章与计时工具皆“按原样”提供。虽然我们力求资讯的科学性与准确性，但咖啡冲煮受到诸多实体变数（如水质、豆种、气温等）影响。",
      "terms.s3.l1": "我们对本网站内容的绝对准确性、完整性或适用性不作任何明示或暗示的保证。",
      "terms.s3.l2": "对于因使用本网站工具或依赖本网站资讯而造成的任何直接、间接或附带损失（包括但不限于咖啡豆的损耗或设备的损坏），Barista Flow 概不负责。",
      "terms.s4.title": "用户行为规范",
      "terms.s4.p1": "在使用本网站时，您同意遵守所有适用的法律法规，并且不得：",
      "terms.s4.l1": "以任何可能导致本网站服务器或网络负载过重、受损或中断的方式使用本网站（例如进行 DDoS 攻击或恶意爬虫抓取）。",
      "terms.s4.l2": "试图未经授权访问本网站的后台系统或源代码。",
      "terms.s4.l3": "利用本网站从事任何违法或欺诈行为。",
      "terms.s5.title": "第三方服务与广告",
      "terms.s5.p1": "本网站可能包含第三方网站的链接或展示第三方广告（如 Google AdSense）。我们无法控制这些第三方网站的内容与隐私政策。点击广告或外部链接产生的任何风险，由用户自行承担。",
      "terms.s6.title": "条款的修改与终止",
      "terms.s6.p1": "我们保留随时修改、暂停或终止本网站服务及本服务条款的权利，恕不另行通知。您继续使用本网站即表示您接受任何修改后的条款。",
    }
  },
  "en": {
    "about": {
      "about.meta.title": "About Us | Barista Flow",
      "about.meta.desc": "Discover the mission of Barista Flow. We are dedicated to digitizing coffee science and creating the world's most professional specialty coffee brewing tools.",
      "about.title": "About Us",
      "about.intro": "In the world of specialty coffee, subtle variables determine the final flavor. Barista Flow was born to solve a problem every coffee lover faces: 'How do we make every brew stable, precise, and scientifically grounded?'",
      "about.vision.title": "Our Vision",
      "about.vision.p1": "We are a group of developers and baristas passionate about coffee. We believe that a good cup of coffee shouldn't rely solely on 'feeling' or 'luck'. Water temperature, brew ratio, grind size, and crucial fluid dynamics (pouring rhythm) can all be quantified and controlled using scientific data.",
      "about.vision.p2": "is to build the world's most professional and easy-to-use coffee brewing tool platform, allowing everyone from pour-over beginners to seasoned baristas to find answers to elevate their extraction quality.",
      "about.offer.title": "What We Offer",
      "about.offer.l1.title": "Interactive 3-Stage Timer",
      "about.offer.l1": "Instantly calculate the optimal pouring timing and water volume targets for bloom, main extraction, and the final phase based on your bean type and brew ratio.",
      "about.offer.l2.title": "Recipe Saving & Sharing",
      "about.offer.l2": "Allows you to save every successful recipe and share your brewing philosophy with coffee enthusiasts worldwide via a dedicated link.",
      "about.offer.l3.title": "In-Depth Knowledge Base",
      "about.offer.l3": "We don't write empty articles. Our knowledge base dives deep into fluid dynamics, the Maillard reaction, and the physical limits of extraction yield, helping you understand the 'why' behind the 'how'.",
      "about.promise.title": "Our Promise",
      "about.promise.p1": "Barista Flow promises to keep its core tools permanently free. We are committed to providing an ultimate, distraction-free user experience (including a carefully designed dark mode and smooth animations), because we know that during those three minutes of focused brewing, you shouldn't be bothered by a poor interface.",
      "about.quote": "Precision is the only path to ultimate flavor.",
    },
    "terms": {
      "terms.meta.title": "Terms of Service | Barista Flow",
      "terms.meta.desc": "Barista Flow Terms of Service. Regulations on website usage, intellectual property, and disclaimers.",
      "terms.intro": "Welcome to Barista Flow ('the Website'). By browsing, accessing, or using any tools and content provided by this Website, you fully agree to and accept the following terms of service. If you do not agree with any part of these terms, please do not use this Website.",
      "terms.s1.p1": "Barista Flow provides free online coffee brewing timers, parameter calculation tools, and knowledge articles related to coffee science. This website is intended for personal, non-commercial reference and assistance.",
      "terms.s2.title": "Intellectual Property",
      "terms.s2.p1": "All content on this Website, including but not limited to text, logos, images, charts, application code, UI design, and architecture, is the property of the Barista Flow team or has been legally authorized for use.",
      "terms.s2.l1": "Without our prior written permission, you may not copy, modify, distribute, publish, display, or use the content of this Website for any commercial purposes.",
      "terms.s2.l2": "You may share links to this Website for personal learning purposes (for example, using our 'Share this recipe' feature).",
      "terms.s3.p1": "All coffee parameters, instructional articles, and timing tools provided by this Website are provided 'as is'. While we strive for scientific accuracy, coffee brewing is affected by many physical variables (such as water quality, bean type, temperature, etc.).",
      "terms.s3.l1": "We make no express or implied warranties regarding the absolute accuracy, completeness, or applicability of the content on this Website.",
      "terms.s3.l2": "Barista Flow is not responsible for any direct, indirect, or incidental losses (including but not limited to the loss of coffee beans or damage to equipment) caused by using the tools on this Website or relying on the information on this Website.",
      "terms.s4.title": "User Conduct",
      "terms.s4.p1": "When using this Website, you agree to comply with all applicable laws and regulations, and you must not:",
      "terms.s4.l1": "Use this Website in any way that could cause the Website's server or network to be overloaded, damaged, or interrupted (e.g., DDoS attacks or malicious scraping).",
      "terms.s4.l2": "Attempt to gain unauthorized access to the Website's backend system or source code.",
      "terms.s4.l3": "Use this Website to engage in any illegal or fraudulent activities.",
      "terms.s5.title": "Third-Party Services and Ads",
      "terms.s5.p1": "This Website may contain links to third-party websites or display third-party advertisements (such as Google AdSense). We have no control over the content and privacy policies of these third-party websites. Any risks arising from clicking on ads or external links are the sole responsibility of the user.",
      "terms.s6.title": "Modification and Termination",
      "terms.s6.p1": "We reserve the right to modify, suspend, or terminate the services of this Website and these Terms of Service at any time without prior notice. Your continued use of this Website constitutes your acceptance of any modified terms.",
    }
  },
  "fr": {
    "about": {
      "about.meta.title": "À propos de nous | Barista Flow",
      "about.meta.desc": "Découvrez la mission de Barista Flow. Nous nous consacrons à la numérisation de la science du café et à la création des outils de préparation de café de spécialité les plus professionnels au monde.",
      "about.title": "À propos de nous",
      "about.intro": "Dans le monde du café de spécialité, de subtiles variables déterminent la saveur finale. Barista Flow est né pour résoudre un problème auquel tout amateur de café est confronté : 'Comment rendre chaque infusion stable, précise et scientifiquement fondée ?'",
      "about.vision.title": "Notre Vision",
      "about.vision.p1": "Nous sommes un groupe de développeurs et de baristas passionnés par le café. Nous pensons qu'une bonne tasse de café ne devrait pas reposer uniquement sur le 'ressenti' ou la 'chance'. La température de l'eau, le ratio d'infusion, la taille de mouture et la dynamique des fluides (rythme de versement) peuvent tous être quantifiés et contrôlés grâce à des données scientifiques.",
      "about.vision.p2": "est de construire la plateforme d'outils de préparation de café la plus professionnelle et la plus facile à utiliser au monde, permettant à chacun, des débutants aux baristas chevronnés, de trouver des réponses pour améliorer la qualité de leur extraction.",
      "about.offer.title": "Ce que nous offrons",
      "about.offer.l1.title": "Minuteur interactif à 3 étapes",
      "about.offer.l1": "Calcule instantanément le temps de versement optimal et les volumes d'eau pour la pré-infusion, l'extraction principale et la phase finale en fonction de votre type de grain et de votre ratio.",
      "about.offer.l2.title": "Sauvegarde et partage de recettes",
      "about.offer.l2": "Vous permet de sauvegarder chaque recette réussie et de partager votre philosophie de préparation avec des passionnés de café du monde entier via un lien dédié.",
      "about.offer.l3.title": "Base de connaissances approfondie",
      "about.offer.l3": "Nous n'écrivons pas d'articles vides. Notre base de connaissances plonge au cœur de la dynamique des fluides, de la réaction de Maillard et des limites physiques du rendement d'extraction, pour vous aider à comprendre le 'pourquoi' derrière le 'comment'.",
      "about.promise.title": "Notre Promesse",
      "about.promise.p1": "Barista Flow promet de garder ses outils principaux gratuits pour toujours. Nous nous engageons à offrir une expérience utilisateur ultime et sans distraction (y compris un mode sombre soigné et des animations fluides), car nous savons que pendant ces trois minutes de préparation concentrée, vous ne devriez pas être dérangé par une mauvaise interface.",
      "about.quote": "La précision est le seul chemin vers la saveur ultime.",
    },
    "terms": {
      "terms.meta.title": "Conditions de Service | Barista Flow",
      "terms.meta.desc": "Conditions de service de Barista Flow. Règles d'utilisation du site web, propriété intellectuelle et clauses de non-responsabilité.",
      "terms.intro": "Bienvenue sur Barista Flow ('le Site Web'). En naviguant, accédant ou utilisant tout outil et contenu fourni par ce Site Web, vous acceptez pleinement et sans réserve les conditions de service suivantes. Si vous n'êtes pas d'accord avec une partie de ces conditions, veuillez ne pas utiliser ce Site Web.",
      "terms.s1.p1": "Barista Flow fournit des minuteurs de préparation de café en ligne gratuits, des outils de calcul de paramètres et des articles de connaissances liés à la science du café. Ce site web est destiné à une référence et une assistance personnelles et non commerciales.",
      "terms.s2.title": "Propriété Intellectuelle",
      "terms.s2.p1": "Tout le contenu de ce Site Web, y compris mais sans s'y limiter, les textes, logos, images, graphiques, code d'application, design de l'interface et architecture, est la propriété de l'équipe Barista Flow ou a été légalement autorisé pour utilisation.",
      "terms.s2.l1": "Sans notre autorisation écrite préalable, vous ne pouvez pas copier, modifier, distribuer, publier, afficher ou utiliser le contenu de ce Site Web à des fins commerciales.",
      "terms.s2.l2": "Vous pouvez partager des liens vers ce Site Web à des fins d'apprentissage personnel (par exemple, en utilisant notre fonctionnalité 'Partager cette recette').",
      "terms.s3.p1": "Tous les paramètres de café, articles d'instruction et outils de minuterie fournis par ce Site Web sont fournis 'tels quels'. Bien que nous nous efforcions d'assurer l'exactitude scientifique, la préparation du café est affectée par de nombreuses variables physiques (telles que la qualité de l'eau, le type de grain, la température, etc.).",
      "terms.s3.l1": "Nous ne donnons aucune garantie expresse ou implicite concernant l'exactitude absolue, l'exhaustivité ou l'applicabilité du contenu de ce Site Web.",
      "terms.s3.l2": "Barista Flow n'est pas responsable des pertes directes, indirectes ou accessoires (y compris, mais sans s'y limiter, la perte de grains de café ou les dommages à l'équipement) causées par l'utilisation des outils de ce Site Web ou la confiance accordée aux informations de ce Site Web.",
      "terms.s4.title": "Conduite de l'utilisateur",
      "terms.s4.p1": "Lors de l'utilisation de ce Site Web, vous acceptez de vous conformer à toutes les lois et réglementations applicables, et vous ne devez pas :",
      "terms.s4.l1": "Utiliser ce Site Web d'une manière qui pourrait surcharger, endommager ou interrompre le serveur ou le réseau du Site Web (par exemple, attaques DDoS ou grattage malveillant).",
      "terms.s4.l2": "Tenter d'obtenir un accès non autorisé au système backend ou au code source du Site Web.",
      "terms.s4.l3": "Utiliser ce Site Web pour vous engager dans des activités illégales ou frauduleuses.",
      "terms.s5.title": "Services tiers et publicités",
      "terms.s5.p1": "Ce Site Web peut contenir des liens vers des sites Web tiers ou afficher des publicités tierces (telles que Google AdSense). Nous n'avons aucun contrôle sur le contenu et les politiques de confidentialité de ces sites Web tiers. Tout risque découlant du clic sur des annonces ou des liens externes relève de la seule responsabilité de l'utilisateur.",
      "terms.s6.title": "Modification et Résiliation",
      "terms.s6.p1": "Nous nous réservons le droit de modifier, suspendre ou résilier les services de ce Site Web et ces Conditions de Service à tout moment et sans préavis. Votre utilisation continue de ce Site Web constitue votre acceptation de toutes conditions modifiées.",
    }
  },
  "ja": {
    "about": {
      "about.meta.title": "私たちについて | Barista Flow",
      "about.meta.desc": "Barista Flow の使命をご覧ください。私たちはコーヒー科学のデジタル化と、世界で最もプロフェッショナルなスペシャルティコーヒー抽出ツールの作成に専念しています。",
      "about.title": "私たちについて",
      "about.intro": "スペシャルティコーヒーの世界では、微妙な変数が最終的な風味を決定します。Barista Flowは、すべてのコーヒー愛好家が直面する「すべての抽出を安定させ、正確に、科学的根拠に基づいて行うにはどうすればよいか？」という問題を解決するために生まれました。",
      "about.vision.title": "私たちのビジョン",
      "about.vision.p1": "私たちは、コーヒーに情熱を注ぐ開発者とバリスタのグループです。美味しいコーヒーは「感覚」や「運」だけに頼るべきではないと信じています。水温、抽出比率、挽き具合、そして重要な流体力学（注ぐリズム）はすべて、科学的データを使用して数値化および制御できます。",
      "about.vision.p2": "は、世界で最もプロフェッショナルで使いやすいコーヒー抽出ツールプラットフォームを構築し、ドリップ初心者からベテランバリスタまで、誰もが抽出の質を高めるための答えを見つけられるようにすることです。",
      "about.offer.title": "私たちが提供するもの",
      "about.offer.l1.title": "インタラクティブな3段階タイマー",
      "about.offer.l1": "豆の種類と抽出比率に基づいて、蒸らし、メイン抽出、および最終段階の最適な注水タイミングと目標水量を即座に計算します。",
      "about.offer.l2.title": "レシピの保存と共有",
      "about.offer.l2": "成功した各レシピを保存し、専用リンクを介して世界中のコーヒー愛好家とあなたの抽出哲学を共有できます。",
      "about.offer.l3.title": "詳細な知識ベース",
      "about.offer.l3": "私たちは内容のない記事は書きません。私たちの知識ベースは、流体力学、メイラード反応、および抽出収率の物理的限界を深く掘り下げ、「どのように」の背後にある「なぜ」を理解するのに役立ちます。",
      "about.promise.title": "私たちの約束",
      "about.promise.p1": "Barista Flow は、コアツールを永久に無料で提供し続けることをお約束します。私たちは、究極の、気を散らさないユーザーエクスペリエンス（慎重に設計されたダークモードとスムーズなアニメーションを含む）を提供することをお約束します。なぜなら、集中して抽出するその3分間は、貧弱なインターフェースに悩まされるべきではないと私たちが知っているからです。",
      "about.quote": "精度こそが究極の風味への唯一の道です。",
    },
    "terms": {
      "terms.meta.title": "利用規約 | Barista Flow",
      "terms.meta.desc": "Barista Flow 利用規約。ウェブサイトの利用、知的財産、免責事項に関する規定。",
      "terms.intro": "Barista Flow（以下「本ウェブサイト」）へようこそ。本ウェブサイトが提供するツールやコンテンツを閲覧、アクセス、または利用することにより、お客様は以下の利用規約に完全に同意し、受け入れたものとみなされます。これらの条件のいずれかの部分に同意しない場合は、本ウェブサイトを使用しないでください。",
      "terms.s1.p1": "Barista Flow は、無料のオンラインコーヒー抽出タイマー、パラメータ計算ツール、およびコーヒー科学に関する知識記事を提供します。本ウェブサイトは、個人的かつ非営利的な参考および支援を目的としています。",
      "terms.s2.title": "知的財産権",
      "terms.s2.p1": "本ウェブサイト上のすべてのコンテンツ（テキスト、ロゴ、画像、チャート、アプリケーションコード、UIデザイン、およびアーキテクチャを含みますがこれらに限定されません）は、Barista Flow チームの所有物であるか、合法的に使用が許可されています。",
      "terms.s2.l1": "事前の書面による許可なしに、商業目的で本ウェブサイトのコンテンツをコピー、変更、配布、公開、表示、または使用することはできません。",
      "terms.s2.l2": "個人的な学習目的で本ウェブサイトへのリンクを共有することは許可されています（例：「このレシピを共有する」機能の使用）。",
      "terms.s3.p1": "本ウェブサイトで提供されるすべてのコーヒーパラメータ、説明記事、およびタイミングツールは「現状有姿」で提供されます。私たちは科学的な正確さに努めていますが、コーヒーの抽出は多くの物理的変数（水質、豆の種類、温度など）の影響を受けます。",
      "terms.s3.l1": "本ウェブサイトのコンテンツの絶対的な正確性、完全性、または適用性について、明示または黙示を問わずいかなる保証も行いません。",
      "terms.s3.l2": "Barista Flow は、本ウェブサイトのツールを使用したり、本ウェブサイトの情報に依存したことによって引き起こされた直接的、間接的、または付随的な損失（コーヒー豆の損失や機器の損傷を含みますがこれらに限定されません）について責任を負いません。",
      "terms.s4.title": "ユーザーの行動",
      "terms.s4.p1": "本ウェブサイトを利用する際、適用されるすべての法律および規制を遵守することに同意し、以下の行為を行ってはなりません。",
      "terms.s4.l1": "本ウェブサイトのサーバーやネットワークに過負荷をかけたり、損傷を与えたり、中断させたりする可能性のある方法で本ウェブサイトを使用すること（DDoS攻撃や悪意のあるスクレイピングなど）。",
      "terms.s4.l2": "本ウェブサイトのバックエンドシステムまたはソースコードへの不正アクセスを試みること。",
      "terms.s4.l3": "本ウェブサイトを利用して、違法または詐欺的な活動に関与すること。",
      "terms.s5.title": "サードパーティのサービスと広告",
      "terms.s5.p1": "本ウェブサイトには、サードパーティのウェブサイトへのリンクが含まれている場合や、サードパーティの広告（Google AdSenseなど）が表示される場合があります。私たちは、これらのサードパーティのウェブサイトのコンテンツおよびプライバシーポリシーを管理することはできません。広告または外部リンクをクリックすることによって生じるリスクは、ユーザーの単独の責任となります。",
      "terms.s6.title": "変更および終了",
      "terms.s6.p1": "私たちは、事前の通知なしに、いつでも本ウェブサイトのサービスおよび本利用規約を変更、一時停止、または終了する権利を留保します。本ウェブサイトを継続して使用することにより、変更された条件に同意したものとみなされます。",
    }
  },
  "de": {
    "about": {
      "about.meta.title": "Über uns | Barista Flow",
      "about.meta.desc": "Entdecken Sie die Mission von Barista Flow. Wir widmen uns der Digitalisierung der Kaffeewissenschaft und der Entwicklung der weltweit professionellsten Werkzeuge für die Zubereitung von Spezialitätenkaffee.",
      "about.title": "Über uns",
      "about.intro": "In der Welt des Spezialitätenkaffees bestimmen subtile Variablen den endgültigen Geschmack. Barista Flow wurde geboren, um ein Problem zu lösen, mit dem jeder Kaffeeliebhaber konfrontiert ist: 'Wie machen wir jeden Aufguss stabil, präzise und wissenschaftlich fundiert?'",
      "about.vision.title": "Unsere Vision",
      "about.vision.p1": "Wir sind eine Gruppe von Entwicklern und Baristas mit einer Leidenschaft für Kaffee. Wir glauben, dass eine gute Tasse Kaffee nicht nur von 'Gefühl' oder 'Glück' abhängen sollte. Wassertemperatur, Brühverhältnis, Mahlgrad und die entscheidende Fluiddynamik (Gießrhythmus) können alle durch wissenschaftliche Daten quantifiziert und kontrolliert werden.",
      "about.vision.p2": "ist es, die weltweit professionellste und benutzerfreundlichste Plattform für Kaffeezubereitungswerkzeuge aufzubauen, die es jedem, vom Anfänger bis zum erfahrenen Barista, ermöglicht, Antworten zu finden, um seine Extraktionsqualität zu verbessern.",
      "about.offer.title": "Was wir anbieten",
      "about.offer.l1.title": "Interaktiver 3-Stufen-Timer",
      "about.offer.l1": "Berechnen Sie basierend auf Ihrer Bohnenart und dem Brühverhältnis sofort das optimale Gieß-Timing und die Zielwassermenge für das Blooming, die Hauptextraktion und die Endphase.",
      "about.offer.l2.title": "Rezeptspeicherung & Teilen",
      "about.offer.l2": "Ermöglicht es Ihnen, jedes erfolgreiche Rezept zu speichern und Ihre Brühphilosophie über einen speziellen Link mit Kaffeeliebhabern weltweit zu teilen.",
      "about.offer.l3.title": "Tiefgehende Wissensdatenbank",
      "about.offer.l3": "Wir schreiben keine leeren Artikel. Unsere Wissensdatenbank taucht tief in die Fluiddynamik, die Maillard-Reaktion und die physikalischen Grenzen der Extraktionsausbeute ein und hilft Ihnen, das 'Warum' hinter dem 'Wie' zu verstehen.",
      "about.promise.title": "Unser Versprechen",
      "about.promise.p1": "Barista Flow verspricht, seine Kernwerkzeuge dauerhaft kostenlos zu halten. Wir verpflichten uns, ein ultimatives, ablenkungsfreies Benutzererlebnis zu bieten (einschließlich eines sorgfältig gestalteten Dunkelmodus und flüssiger Animationen), da wir wissen, dass Sie sich während dieser drei Minuten konzentrierten Brühens nicht von einer schlechten Benutzeroberfläche stören lassen sollten.",
      "about.quote": "Präzision ist der einzige Weg zum ultimativen Geschmack.",
    },
    "terms": {
      "terms.meta.title": "Nutzungsbedingungen | Barista Flow",
      "terms.meta.desc": "Barista Flow Nutzungsbedingungen. Bestimmungen zur Nutzung der Website, zum geistigen Eigentum und Haftungsausschlüsse.",
      "terms.intro": "Willkommen bei Barista Flow ('die Website'). Durch das Durchsuchen, Aufrufen oder Verwenden von Tools und Inhalten, die von dieser Website bereitgestellt werden, stimmen Sie den folgenden Nutzungsbedingungen vollständig zu und akzeptieren diese. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, verwenden Sie diese Website bitte nicht.",
      "terms.s1.p1": "Barista Flow bietet kostenlose Online-Timer für die Kaffeezubereitung, Tools zur Parameterberechnung und Wissensartikel zur Kaffeewissenschaft. Diese Website ist für persönliche, nichtkommerzielle Referenz und Unterstützung vorgesehen.",
      "terms.s2.title": "Geistiges Eigentum",
      "terms.s2.p1": "Alle Inhalte auf dieser Website, einschließlich, aber nicht beschränkt auf Texte, Logos, Bilder, Diagramme, Anwendungscode, UI-Design und Architektur, sind Eigentum des Barista Flow-Teams oder wurden rechtmäßig zur Nutzung autorisiert.",
      "terms.s2.l1": "Ohne unsere vorherige schriftliche Genehmigung dürfen Sie den Inhalt dieser Website nicht für kommerzielle Zwecke kopieren, ändern, verteilen, veröffentlichen, anzeigen oder verwenden.",
      "terms.s2.l2": "Sie dürfen Links zu dieser Website für persönliche Lernzwecke teilen (z. B. über unsere Funktion 'Dieses Rezept teilen').",
      "terms.s3.p1": "Alle von dieser Website bereitgestellten Kaffeeparameter, Anleitungsartikel und Timing-Tools werden 'wie besehen' bereitgestellt. Während wir uns um wissenschaftliche Genauigkeit bemühen, wird die Kaffeezubereitung von vielen physikalischen Variablen beeinflusst (wie Wasserqualität, Bohnenart, Temperatur usw.).",
      "terms.s3.l1": "Wir übernehmen keine ausdrückliche oder stillschweigende Garantie in Bezug auf die absolute Genauigkeit, Vollständigkeit oder Anwendbarkeit der Inhalte auf dieser Website.",
      "terms.s3.l2": "Barista Flow ist nicht verantwortlich für direkte, indirekte oder zufällige Verluste (einschließlich, aber nicht beschränkt auf den Verlust von Kaffeebohnen oder Schäden an Geräten), die durch die Verwendung der Tools auf dieser Website oder das Vertrauen auf die Informationen auf dieser Website entstehen.",
      "terms.s4.title": "Nutzerverhalten",
      "terms.s4.p1": "Bei der Nutzung dieser Website erklären Sie sich damit einverstanden, alle geltenden Gesetze und Vorschriften einzuhalten, und Sie dürfen nicht:",
      "terms.s4.l1": "Diese Website auf eine Weise nutzen, die dazu führen könnte, dass der Server oder das Netzwerk der Website überlastet, beschädigt oder unterbrochen wird (z. B. DDoS-Angriffe oder böswilliges Scraping).",
      "terms.s4.l2": "Versuchen, unbefugten Zugriff auf das Backend-System oder den Quellcode der Website zu erlangen.",
      "terms.s4.l3": "Diese Website nutzen, um sich an illegalen oder betrügerischen Aktivitäten zu beteiligen.",
      "terms.s5.title": "Dienste und Werbung von Drittanbietern",
      "terms.s5.p1": "Diese Website kann Links zu Websites Dritter enthalten oder Werbung Dritter anzeigen (z. B. Google AdSense). Wir haben keine Kontrolle über den Inhalt und die Datenschutzrichtlinien dieser Websites Dritter. Alle Risiken, die durch das Klicken auf Anzeigen oder externe Links entstehen, liegen in der alleinigen Verantwortung des Nutzers.",
      "terms.s6.title": "Änderung und Beendigung",
      "terms.s6.p1": "Wir behalten uns das Recht vor, die Dienste dieser Website und diese Nutzungsbedingungen jederzeit ohne vorherige Ankündigung zu ändern, auszusetzen oder zu beenden. Ihre fortgesetzte Nutzung dieser Website stellt Ihre Zustimmung zu allen geänderten Bedingungen dar.",
    }
  },
  "es": {
    "about": {
      "about.meta.title": "Sobre nosotros | Barista Flow",
      "about.meta.desc": "Descubre la misión de Barista Flow. Nos dedicamos a digitalizar la ciencia del café y crear las herramientas de preparación de café de especialidad más profesionales del mundo.",
      "about.title": "Sobre nosotros",
      "about.intro": "En el mundo del café de especialidad, sutiles variables determinan el sabor final. Barista Flow nació para resolver un problema al que se enfrenta todo amante del café: '¿Cómo hacemos que cada infusión sea estable, precisa y con base científica?'",
      "about.vision.title": "Nuestra Visión",
      "about.vision.p1": "Somos un grupo de desarrolladores y baristas apasionados por el café. Creemos que una buena taza de café no debería depender únicamente del 'sentimiento' o la 'suerte'. La temperatura del agua, la proporción de preparación, el tamaño de la molienda y la dinámica de fluidos crucial (ritmo de vertido) pueden cuantificarse y controlarse utilizando datos científicos.",
      "about.vision.p2": "es construir la plataforma de herramientas de preparación de café más profesional y fácil de usar del mundo, permitiendo a todos, desde principiantes hasta baristas experimentados, encontrar respuestas para elevar la calidad de su extracción.",
      "about.offer.title": "Lo que ofrecemos",
      "about.offer.l1.title": "Temporizador Interactivo de 3 Etapas",
      "about.offer.l1": "Calcula al instante el momento óptimo de vertido y los objetivos de volumen de agua para el bloom, la extracción principal y la fase final en función de tu tipo de grano y proporción.",
      "about.offer.l2.title": "Guardado y Compartición de Recetas",
      "about.offer.l2": "Te permite guardar cada receta exitosa y compartir tu filosofía de preparación con entusiastas del café de todo el mundo a través de un enlace dedicado.",
      "about.offer.l3.title": "Base de Conocimientos Profunda",
      "about.offer.l3": "No escribimos artículos vacíos. Nuestra base de conocimientos profundiza en la dinámica de fluidos, la reacción de Maillard y los límites físicos del rendimiento de extracción, ayudándote a entender el 'por qué' detrás del 'cómo'.",
      "about.promise.title": "Nuestra Promesa",
      "about.promise.p1": "Barista Flow promete mantener sus herramientas principales permanentemente gratuitas. Estamos comprometidos a proporcionar una experiencia de usuario definitiva y sin distracciones (incluido un modo oscuro cuidadosamente diseñado y animaciones fluidas), porque sabemos que durante esos tres minutos de preparación enfocada, no deberías distraerte con una mala interfaz.",
      "about.quote": "La precisión es el único camino hacia el sabor definitivo.",
    },
    "terms": {
      "terms.meta.title": "Términos de Servicio | Barista Flow",
      "terms.meta.desc": "Términos de Servicio de Barista Flow. Regulaciones sobre el uso del sitio web, propiedad intelectual y descargos de responsabilidad.",
      "terms.intro": "Bienvenido a Barista Flow ('el Sitio Web'). Al navegar, acceder o utilizar cualquier herramienta y contenido proporcionado por este Sitio Web, aceptas plenamente y sin reservas los siguientes términos de servicio. Si no estás de acuerdo con alguna parte de estos términos, no utilices este Sitio Web.",
      "terms.s1.p1": "Barista Flow proporciona temporizadores de preparación de café en línea gratuitos, herramientas de cálculo de parámetros y artículos de conocimiento relacionados con la ciencia del café. Este sitio web está destinado a fines de referencia y asistencia personal, no comercial.",
      "terms.s2.title": "Propiedad Intelectual",
      "terms.s2.p1": "Todo el contenido de este Sitio Web, incluyendo pero no limitado a textos, logotipos, imágenes, gráficos, código de aplicación, diseño de interfaz y arquitectura, es propiedad del equipo de Barista Flow o ha sido legalmente autorizado para su uso.",
      "terms.s2.l1": "Sin nuestro permiso previo por escrito, no puedes copiar, modificar, distribuir, publicar, mostrar ni utilizar el contenido de este Sitio Web con fines comerciales.",
      "terms.s2.l2": "Puedes compartir enlaces a este Sitio Web con fines de aprendizaje personal (por ejemplo, utilizando nuestra función 'Compartir esta receta').",
      "terms.s3.p1": "Todos los parámetros de café, artículos instructivos y herramientas de temporización proporcionados por este Sitio Web se proporcionan 'tal cual'. Si bien nos esforzamos por mantener la precisión científica, la preparación del café se ve afectada por muchas variables físicas (como la calidad del agua, el tipo de grano, la temperatura, etc.).",
      "terms.s3.l1": "No ofrecemos garantías explícitas o implícitas sobre la precisión absoluta, la integridad o la aplicabilidad del contenido de este Sitio Web.",
      "terms.s3.l2": "Barista Flow no se hace responsable de las pérdidas directas, indirectes o incidentales (incluyendo, entre otras, la pérdida de granos de café o daños en el equipo) causadas por el uso de las herramientas de este Sitio Web o por depender de la información de este Sitio Web.",
      "terms.s4.title": "Conducta del Usuario",
      "terms.s4.p1": "Al utilizar este Sitio Web, aceptas cumplir con todas las leyes y regulaciones aplicables, y no debes:",
      "terms.s4.l1": "Utilizar este Sitio Web de ninguna manera que pueda causar que el servidor o la red del Sitio Web se sobrecarguen, dañen o interrumpan (por ejemplo, ataques DDoS o scraping malicioso).",
      "terms.s4.l2": "Intentar obtener acceso no autorizado al sistema backend o al código fuente del Sitio Web.",
      "terms.s4.l3": "Utilizar este Sitio Web para participar en actividades ilegales o fraudulentas.",
      "terms.s5.title": "Servicios de Terceros y Publicidad",
      "terms.s5.p1": "Este Sitio Web puede contener enlaces a sitios web de terceros o mostrar publicidad de terceros (como Google AdSense). No tenemos control sobre el contenido y las políticas de privacidad de estos sitios web de terceros. Cualquier riesgo derivado de hacer clic en anuncios o enlaces externos es responsabilidad exclusiva del usuario.",
      "terms.s6.title": "Modificación y Terminación",
      "terms.s6.p1": "Nos reservamos el derecho de modificar, suspender o cancelar los servicios de este Sitio Web y estos Términos de Servicio en cualquier momento sin previo aviso. Tu uso continuo de este Sitio Web constituye tu aceptación de cualquier término modificado.",
    }
  },
  "pt": {
    "about": {
      "about.meta.title": "Sobre nós | Barista Flow",
      "about.meta.desc": "Descubra a missão da Barista Flow. Dedicamo-nos a digitalizar a ciência do café e a criar as ferramentas de preparação de café de especialidade mais profissionais do mundo.",
      "about.title": "Sobre nós",
      "about.intro": "No mundo do café de especialidade, variáveis sutis determinam o sabor final. A Barista Flow nasceu para resolver um problema que todo amante de café enfrenta: 'Como tornamos cada extração estável, precisa e com base científica?'",
      "about.vision.title": "Nossa Visão",
      "about.vision.p1": "Somos um grupo de desenvolvedores e baristas apaixonados por café. Acreditamos que uma boa xícara de café não deve depender apenas de 'sentimento' ou 'sorte'. Temperatura da água, proporção de infusão, tamanho da moagem e a crucial dinâmica de fluidos (ritmo de despejo) podem ser quantificados e controlados usando dados científicos.",
      "about.vision.p2": "é construir a plataforma de ferramentas de extração de café mais profissional e fácil de usar do mundo, permitindo que todos, desde iniciantes em métodos coados até baristas experientes, encontrem respostas para elevar a qualidade de sua extração.",
      "about.offer.title": "O Que Oferecemos",
      "about.offer.l1.title": "Temporizador Interativo de 3 Estágios",
      "about.offer.l1": "Calcule instantaneamente o momento ideal de despejo e os volumes de água para a pré-infusão, extração principal e fase final com base no seu tipo de grão e proporção.",
      "about.offer.l2.title": "Salvamento e Compartilhamento de Receitas",
      "about.offer.l2": "Permite salvar cada receita bem-sucedida e compartilhar sua filosofia de extração com entusiastas de café em todo o mundo através de um link dedicado.",
      "about.offer.l3.title": "Base de Conhecimento Aprofundada",
      "about.offer.l3": "Não escrevemos artigos vazios. Nossa base de conhecimento aprofunda-se na dinâmica de fluidos, na reação de Maillard e nos limites físicos do rendimento de extração, ajudando você a entender o 'porquê' por trás do 'como'.",
      "about.promise.title": "Nossa Promessa",
      "about.promise.p1": "A Barista Flow promete manter suas ferramentas principais permanentemente gratuitas. Estamos comprometidos em fornecer uma experiência de usuário definitiva e sem distrações (incluindo um modo escuro cuidadosamente projetado e animações suaves), porque sabemos que durante aqueles três minutos de extração concentrada, você não deve ser incomodado por uma interface ruim.",
      "about.quote": "A precisão é o único caminho para o sabor definitivo.",
    },
    "terms": {
      "terms.meta.title": "Termos de Serviço | Barista Flow",
      "terms.meta.desc": "Termos de Serviço da Barista Flow. Regulamentos sobre o uso do site, propriedade intelectual e isenções de responsabilidade.",
      "terms.intro": "Bem-vindo à Barista Flow ('o Site'). Ao navegar, acessar ou usar qualquer ferramenta e conteúdo fornecido por este Site, você concorda e aceita totalmente os seguintes termos de serviço. Se você não concordar com qualquer parte destes termos, não use este Site.",
      "terms.s1.p1": "A Barista Flow fornece temporizadores online gratuitos para extração de café, ferramentas de cálculo de parâmetros e artigos de conhecimento relacionados à ciência do café. Este site destina-se a fins de referência e assistência pessoal, não comercial.",
      "terms.s2.title": "Propriedade Intelectual",
      "terms.s2.p1": "Todo o conteúdo deste Site, incluindo, entre outros, textos, logotipos, imagens, gráficos, código de aplicativo, design de interface e arquitetura, é propriedade da equipe Barista Flow ou foi legalmente autorizado para uso.",
      "terms.s2.l1": "Sem nossa permissão prévia por escrito, você não pode copiar, modificar, distribuir, publicar, exibir ou usar o conteúdo deste Site para fins comerciais.",
      "terms.s2.l2": "Você pode compartilhar links para este Site para fins de aprendizado pessoal (por exemplo, usando nossa função 'Compartilhar esta receita').",
      "terms.s3.p1": "Todos os parâmetros de café, artigos instrucionais e ferramentas de temporização fornecidos por este Site são fornecidos 'no estado em que se encontram'. Embora nos esforcemos pela precisão científica, a extração de café é afetada por muitas variáveis físicas (como qualidade da água, tipo de grão, temperatura, etc.).",
      "terms.s3.l1": "Não oferecemos garantias explícitas ou implícitas em relação à precisão absoluta, integridade ou aplicabilidade do conteúdo deste Site.",
      "terms.s3.l2": "A Barista Flow não se responsabiliza por quaisquer perdas diretas, indiretas ou incidentais (incluyendo, entre outras, perda de grãos de café ou danos a equipamentos) causadas pelo uso das ferramentas deste Site ou pela confiança nas informações deste Site.",
      "terms.s4.title": "Conduta do Usuário",
      "terms.s4.p1": "Ao utilizar este Site, você concorda em cumprir todas as leis e regulamentos aplicáveis, e você não deve:",
      "terms.s4.l1": "Utilizar este Site de qualquer forma que possa causar sobrecarga, danos ou interrupção do servidor ou da rede do Site (por exemplo, ataques DDoS ou raspagem maliciosa de dados).",
      "terms.s4.l2": "Tentar obter acesso não autorizado ao sistema back-end ou ao código-fonte do Site.",
      "terms.s4.l3": "Utilizar este Site para se envolver em atividades ilegais ou fraudulentas.",
      "terms.s5.title": "Serviços de Terceiros e Publicidade",
      "terms.s5.p1": "Este Site pode conter links para sites de terceiros ou exibir anúncios de terceiros (como o Google AdSense). Não temos controle sobre o conteúdo e as políticas de privacidade desses sites de terceiros. Quaisquer riscos decorrentes do clique em anúncios ou links externos são de responsabilidade exclusiva do usuário.",
      "terms.s6.title": "Modificação e Rescisão",
      "terms.s6.p1": "Reservamo-nos o direito de modificar, suspender ou encerrar os serviços deste Site e estes Termos de Serviço a qualquer momento sem aviso prévio. O uso contínuo deste Site constitui sua aceitação de quaisquer termos modificados.",
    }
  },
  "ru": {
    "about": {
      "about.meta.title": "О нас | Barista Flow",
      "about.meta.desc": "Узнайте о миссии Barista Flow. Мы посвятили себя оцифровке кофейной науки и созданию самых профессиональных в мире инструментов для приготовления спешелти кофе.",
      "about.title": "О нас",
      "about.intro": "В мире спешелти кофе тончайшие переменные определяют окончательный вкус. Barista Flow был создан, чтобы решить проблему, с которой сталкивается каждый любитель кофе: «Как сделать каждую заварку стабильной, точной и научно обоснованной?»",
      "about.vision.title": "Наше видение",
      "about.vision.p1": "Мы — группа разработчиков и бариста, увлеченных кофе. Мы считаем, что хорошая чашка кофе не должна полагаться исключительно на «чувство» или «удачу». Температура воды, соотношение заваривания, размер помола и важнейшая гидродинамика (ритм вливания) — все это можно измерить и контролировать с помощью научных данных.",
      "about.vision.p2": "заключается в создании самой профессиональной и простой в использовании в мире платформы инструментов для заваривания кофе, позволяющей каждому, от новичков до опытных бариста, находить ответы для повышения качества экстракции.",
      "about.offer.title": "Что мы предлагаем",
      "about.offer.l1.title": "Интерактивный 3-х этапный таймер",
      "about.offer.l1": "Мгновенно рассчитывает оптимальное время вливания и целевые объемы воды для предсмачивания, основной экстракции и финальной стадии на основе вашего типа зерна и соотношения.",
      "about.offer.l2.title": "Сохранение и обмен рецептами",
      "about.offer.l2": "Позволяет сохранять каждый успешный рецепт и делиться своей философией заваривания с энтузиастами кофе по всему миру с помощью специальной ссылки.",
      "about.offer.l3.title": "Глубокая база знаний",
      "about.offer.l3": "Мы не пишем пустых статей. Наша база знаний глубоко погружается в гидродинамику, реакцию Майяра и физические пределы выхода экстракции, помогая вам понять «почему» стоит за «как».",
      "about.promise.title": "Наше обещание",
      "about.promise.p1": "Barista Flow обещает, что ее основные инструменты всегда будут бесплатными. Мы стремимся предоставить непревзойденный пользовательский опыт, не отвлекающий внимание (включая тщательно продуманный темный режим и плавную анимацию), потому что мы знаем, что в течение этих трех минут сосредоточенного заваривания вас не должен беспокоить плохой интерфейс.",
      "about.quote": "Точность — единственный путь к идеальному вкусу.",
    },
    "terms": {
      "terms.meta.title": "Условия обслуживания | Barista Flow",
      "terms.meta.desc": "Условия обслуживания Barista Flow. Правила использования веб-сайта, интеллектуальная собственность и отказ от ответственности.",
      "terms.intro": "Добро пожаловать на Barista Flow («Веб-сайт»). Просматривая, получая доступ или используя любые инструменты и контент, предоставленные на этом Веб-сайте, вы полностью соглашаетесь и принимаете следующие условия обслуживания. Если вы не согласны с какой-либо частью этих условий, пожалуйста, не используйте этот Веб-сайт.",
      "terms.s1.p1": "Barista Flow предоставляет бесплатные онлайн-таймеры для заваривания кофе, инструменты расчета параметров и статьи по кофейной науке. Этот веб-сайт предназначен для личного, некоммерческого использования в качестве справки и помощи.",
      "terms.s2.title": "Интеллектуальная собственность",
      "terms.s2.p1": "Весь контент на этом Веб-сайте, включая, помимо прочего, текст, логотипы, изображения, диаграммы, код приложения, дизайн пользовательского интерфейса и архитектуру, является собственностью команды Barista Flow или законно лицензирован для использования.",
      "terms.s2.l1": "Без нашего предварительного письменного разрешения вы не можете копировать, изменять, распространять, публиковать, демонстрировать или использовать контент этого Веб-сайта в коммерческих целях.",
      "terms.s2.l2": "Вы можете делиться ссылками на этот Веб-сайт в целях личного обучения (например, используя нашу функцию «Поделиться этим рецептом»).",
      "terms.s3.p1": "Все параметры кофе, учебные статьи и таймеры, представленные на этом Веб-сайте, предоставляются «как есть». Хотя мы стремимся к научной точности, на заваривание кофе влияют многие физические переменные (такие как качество воды, тип зерен, температура и т. д.).",
      "terms.s3.l1": "Мы не даем никаких явных или подразумеваемых гарантий относительно абсолютной точности, полноты или применимости контента на этом Веб-сайте.",
      "terms.s3.l2": "Barista Flow не несет ответственности за любые прямые, косвенные или случайные убытки (включая, помимо прочего, потерю кофейных зерен или повреждение оборудования), вызванные использованием инструментов этого Веб-сайта или доверием к информации на этом Веб-сайте.",
      "terms.s4.title": "Поведение пользователя",
      "terms.s4.p1": "При использовании этого Веб-сайта вы соглашаетесь соблюдать все применимые законы и правила, и вы не должны:",
      "terms.s4.l1": "Использовать этот Веб-сайт любым способом, который может привести к перегрузке, повреждению или прерыванию работы сервера или сети Веб-сайта (например, DDoS-атаки или вредоносный парсинг).",
      "terms.s4.l2": "Пытаться получить несанкционированный доступ к бэкенд-системе или исходному коду Веб-сайта.",
      "terms.s4.l3": "Использовать этот Веб-сайт для участия в любой незаконной или мошеннической деятельности.",
      "terms.s5.title": "Сторонние сервисы и реклама",
      "terms.s5.p1": "Этот Веб-сайт может содержать ссылки на сторонние веб-сайты или отображать стороннюю рекламу (например, Google AdSense). Мы не контролируем контент и политики конфиденциальности этих сторонних веб-сайтов. Любые риски, возникающие при нажатии на рекламу или внешние ссылки, несет исключительно пользователь.",
      "terms.s6.title": "Изменение и прекращение действия",
      "terms.s6.p1": "Мы оставляем за собой право изменять, приостанавливать или прекращать работу сервисов этого Веб-сайта и настоящих Условий обслуживания в любое время без предварительного уведомления. Продолжение использования вами этого Веб-сайта означает ваше согласие с любыми измененными условиями.",
    }
  },
  "hi": {
    "about": {
      "about.meta.title": "हमारे बारे में | Barista Flow",
      "about.meta.desc": "Barista Flow के मिशन की खोज करें। हम कॉफी विज्ञान को डिजिटल बनाने और दुनिया के सबसे पेशेवर कॉफी ब्रूइंग टूल्स बनाने के लिए समर्पित हैं।",
      "about.title": "हमारे बारे में",
      "about.intro": "स्पेशलिटी कॉफी की दुनिया में, सूक्ष्म चर अंतिम स्वाद का निर्धारण करते हैं। Barista Flow का जन्म हर कॉफी प्रेमी के सामने आने वाली समस्या को हल करने के लिए हुआ था: 'हम हर ब्रू को स्थिर, सटीक और वैज्ञानिक रूप से आधारित कैसे बनाएं?'",
      "about.vision.title": "हमारा विज़न",
      "about.vision.p1": "हम कॉफी के प्रति जुनूनी डेवलपर्स और बरिस्ता का एक समूह हैं। हमारा मानना ​​है कि एक अच्छा कप कॉफी केवल 'भावना' या 'किस्मत' पर निर्भर नहीं होना चाहिए। पानी का तापमान, ब्रू अनुपात, पीसने का आकार, और महत्वपूर्ण द्रव गतिशीलता (डालने की लय) सभी को वैज्ञानिक डेटा का उपयोग करके निर्धारित और नियंत्रित किया जा सकता है।",
      "about.vision.p2": "दुनिया का सबसे पेशेवर और उपयोग में आसान कॉफी ब्रूइंग टूल प्लेटफ़ॉर्म बनाना है, जिससे पोर-ओवर शुरुआती लोगों से लेकर अनुभवी बरिस्ता तक सभी को अपनी निष्कर्षण गुणवत्ता को बढ़ाने के लिए उत्तर मिल सकें।",
      "about.offer.title": "हम क्या प्रदान करते हैं",
      "about.offer.l1.title": "इंटरएक्टिव 3-स्टेज टाइमर",
      "about.offer.l1": "आपके बीन प्रकार और ब्रू अनुपात के आधार पर ब्लूम, मुख्य निष्कर्षण और अंतिम चरण के लिए इष्टतम डालने का समय और पानी की मात्रा के लक्ष्यों की तुरंत गणना करें।",
      "about.offer.l2.title": "रेसिपी सहेजना और साझा करना",
      "about.offer.l2": "आपको हर सफल रेसिपी को सहेजने और एक समर्पित लिंक के माध्यम से दुनिया भर के कॉफी उत्साही लोगों के साथ अपने ब्रूइंग दर्शन को साझा करने की अनुमति देता है।",
      "about.offer.l3.title": "गहन ज्ञानकोष",
      "about.offer.l3": "हम खाली लेख नहीं लिखते हैं। हमारा ज्ञानकोष द्रव गतिशीलता, माइलार्ड प्रतिक्रिया, और निष्कर्षण उपज की भौतिक सीमाओं में गहराई से गोता लगाता है, जिससे आपको 'कैसे' के पीछे के 'क्यों' को समझने में मदद मिलती है।",
      "about.promise.title": "हमारा वादा",
      "about.promise.p1": "Barista Flow अपने मुख्य टूल्स को स्थायी रूप से मुफ़्त रखने का वादा करता है। हम एक परम, व्याकुलता-मुक्त उपयोगकर्ता अनुभव (जिसमें सावधानीपूर्वक डिज़ाइन किया गया डार्क मोड और स्मूथ एनिमेशन शामिल हैं) प्रदान करने के लिए प्रतिबद्ध हैं, क्योंकि हम जानते हैं कि केंद्रित ब्रूइंग के उन तीन मिनटों के दौरान, आपको खराब इंटरफ़ेस से परेशान नहीं होना चाहिए।",
      "about.quote": "सटीकता ही अंतिम स्वाद का एकमात्र मार्ग है।",
    },
    "terms": {
      "terms.meta.title": "सेवा की शर्तें | Barista Flow",
      "terms.meta.desc": "Barista Flow सेवा की शर्तें। वेबसाइट के उपयोग, बौद्धिक संपदा और अस्वीकरण पर नियम।",
      "terms.intro": "Barista Flow ('वेबसाइट') में आपका स्वागत है। इस वेबसाइट द्वारा प्रदान किए गए किसी भी टूल और सामग्री को ब्राउज़, एक्सेस या उपयोग करके, आप निम्नलिखित सेवा की शर्तों से पूरी तरह सहमत हैं और उन्हें स्वीकार करते हैं। यदि आप इन शर्तों के किसी भी हिस्से से सहमत नहीं हैं, तो कृपया इस वेबसाइट का उपयोग न करें।",
      "terms.s1.p1": "Barista Flow मुफ्त ऑनलाइन कॉफी ब्रूइंग टाइमर, पैरामीटर गणना उपकरण और कॉफी विज्ञान से संबंधित ज्ञान लेख प्रदान करता है। यह वेबसाइट व्यक्तिगत, गैर-व्यावसायिक संदर्भ और सहायता के लिए अभिप्रेत है।",
      "terms.s2.title": "बौद्धिक संपदा",
      "terms.s2.p1": "इस वेबसाइट की सभी सामग्री, जिसमें टेक्स्ट, लोगो, चित्र, चार्ट, एप्लिकेशन कोड, यूआई डिज़ाइन और आर्किटेक्चर शामिल हैं, लेकिन इन्हीं तक सीमित नहीं है, Barista Flow टीम की संपत्ति है या उपयोग के लिए कानूनी रूप से अधिकृत है।",
      "terms.s2.l1": "हमारी पूर्व लिखित अनुमति के बिना, आप व्यावसायिक उद्देश्यों के लिए इस वेबसाइट की सामग्री की प्रतिलिपि, संशोधन, वितरण, प्रकाशन, प्रदर्शन या उपयोग नहीं कर सकते हैं।",
      "terms.s2.l2": "आप व्यक्तिगत सीखने के उद्देश्यों के लिए इस वेबसाइट के लिंक साझा कर सकते हैं (उदाहरण के लिए, हमारी 'इस रेसिपी को साझा करें' सुविधा का उपयोग करके)।",
      "terms.s3.p1": "इस वेबसाइट द्वारा प्रदान किए गए सभी कॉफी पैरामीटर, निर्देशात्मक लेख और टाइमिंग टूल 'जैसा है' के आधार पर प्रदान किए जाते हैं। हालांकि हम वैज्ञानिक सटीकता के लिए प्रयास करते हैं, कॉफी ब्रूइंग कई भौतिक चर (जैसे पानी की गुणवत्ता, बीन का प्रकार, तापमान आदि) से प्रभावित होती है।",
      "terms.s3.l1": "हम इस वेबसाइट पर सामग्री की पूर्ण सटीकता, पूर्णता या प्रयोज्यता के संबंध में कोई स्पष्ट या निहित वारंटी नहीं देते हैं।",
      "terms.s3.l2": "इस वेबसाइट के टूल्स का उपयोग करने या इस वेबसाइट की जानकारी पर भरोसा करने के कारण होने वाले किसी भी प्रत्यक्ष, अप्रत्यक्ष या आकस्मिक नुकसान (जिसमें कॉफी बीन्स का नुकसान या उपकरणों की क्षति शामिल है, लेकिन इसी तक सीमित नहीं है) के लिए Barista Flow ज़िम्मेदार नहीं है।",
      "terms.s4.title": "उपयोगकर्ता आचरण",
      "terms.s4.p1": "इस वेबसाइट का उपयोग करते समय, आप सभी लागू कानूनों और विनियमों का पालन करने के लिए सहमत होते हैं, और आपको निम्न कार्य नहीं करने चाहिए:",
      "terms.s4.l1": "इस वेबसाइट का उपयोग किसी भी ऐसे तरीके से करना जो वेबसाइट के सर्वर या नेटवर्क को ओवरलोड, क्षतिग्रस्त या बाधित कर सकता है (जैसे, DDoS हमले या दुर्भावनापूर्ण स्क्रैपिंग)।",
      "terms.s4.l2": "वेबसाइट के बैकएंड सिस्टम या स्रोत कोड तक अनधिकृत पहुंच प्राप्त करने का प्रयास करना।",
      "terms.s4.l3": "किसी भी अवैध या धोखाधड़ी गतिविधियों में शामिल होने के लिए इस वेबसाइट का उपयोग करना।",
      "terms.s5.title": "तृतीय-पक्ष सेवाएँ और विज्ञापन",
      "terms.s5.p1": "इस वेबसाइट में तृतीय-पक्ष वेबसाइटों के लिंक हो सकते हैं या तृतीय-पक्ष विज्ञापन (जैसे Google AdSense) प्रदर्शित हो सकते हैं। इन तृतीय-पक्ष वेबसाइटों की सामग्री और गोपनीयता नीतियों पर हमारा कोई नियंत्रण नहीं है। विज्ञापनों या बाहरी लिंक पर क्लिक करने से उत्पन्न होने वाले किसी भी जोखिम के लिए उपयोगकर्ता पूरी तरह ज़िम्मेदार है।",
      "terms.s6.title": "संशोधन और समाप्ति",
      "terms.s6.p1": "हम बिना किसी पूर्व सूचना के किसी भी समय इस वेबसाइट और इन सेवा की शर्तों को संशोधित, निलंबित या समाप्त करने का अधिकार सुरक्षित रखते हैं। इस वेबसाइट का आपका निरंतर उपयोग किसी भी संशोधित शर्तों की आपकी स्वीकृति का गठन करता है।",
    }
  },
  "bn": {
    "about": {
      "about.meta.title": "আমাদের সম্পর্কে | Barista Flow",
      "about.meta.desc": "Barista Flow এর মিশন সম্পর্কে জানুন। আমরা কফি বিজ্ঞানকে ডিজিটাইজ করতে এবং বিশ্বের সবচেয়ে পেশাদার কফি ব্রুইং টুলস তৈরি করতে নিবেদিত।",
      "about.title": "আমাদের সম্পর্কে",
      "about.intro": "স্পেশালিটি কফির দুনিয়ায়, সূক্ষ্ম বিষয়গুলোই কফির চূড়ান্ত স্বাদ নির্ধারণ করে। Barista Flow এর জন্ম হয়েছে প্রতিটি কফি প্রেমিকের মুখোমুখি হওয়া একটি সমস্যার সমাধান করতে: 'আমরা কীভাবে প্রতিটি ব্রুকে স্থিতিশীল, সুনির্দিষ্ট এবং বৈজ্ঞানিকভাবে ভিত্তিযুক্ত করতে পারি?'",
      "about.vision.title": "আমাদের ভিশন",
      "about.vision.p1": "আমরা একদল ডেভেলপার এবং বারিস্তা যারা কফির প্রতি আগ্রহী। আমরা বিশ্বাস করি যে এক কাপ ভালো কফি শুধুমাত্র 'অনুভূতি' বা 'ভাগ্যের' উপর নির্ভর করা উচিত নয়। জলের তাপমাত্রা, ব্রু অনুপাত, গ্রাইন্ড সাইজ এবং অত্যন্ত গুরুত্বপূর্ণ তরল গতিবিদ্যা (জল ঢালার ছন্দ) সবই বৈজ্ঞানিক ডেটা ব্যবহার করে পরিমাপ এবং নিয়ন্ত্রণ করা যেতে পারে।",
      "about.vision.p2": "হলো বিশ্বের সবচেয়ে পেশাদার এবং সহজেই ব্যবহারযোগ্য কফি ব্রুইং টুল প্ল্যাটফর্ম তৈরি করা, যাতে পোর-ওভার নতুন থেকে শুরু করে অভিজ্ঞ বারিস্তা সবাই তাদের এক্সট্রাকশন মান উন্নত করার উত্তর খুঁজে পেতে পারে।",
      "about.offer.title": "আমরা যা অফার করি",
      "about.offer.l1.title": "ইন্টারেক্টিভ ৩-স্টেজ টাইমার",
      "about.offer.l1": "আপনার কফির বীজের ধরন এবং ব্রু অনুপাতের উপর ভিত্তি করে ব্লুম, প্রধান এক্সট্রাকশন এবং শেষ পর্যায়ের জন্য সর্বোত্তম জল ঢালার সময় এবং জলের পরিমাণের লক্ষ্যগুলি তাৎক্ষণিকভাবে গণনা করুন।",
      "about.offer.l2.title": "রেসিপি সংরক্ষণ এবং শেয়ারিং",
      "about.offer.l2": "আপনাকে প্রতিটি সফল রেসিপি সংরক্ষণ করতে এবং একটি ডেডিকেটেড লিঙ্কের মাধ্যমে বিশ্বব্যাপী কফি উৎসাহীদের সাথে আপনার ব্রুইং দর্শন শেয়ার করার অনুমতি দেয়।",
      "about.offer.l3.title": "গভীর জ্ঞানের ভিত্তি",
      "about.offer.l3": "আমরা ফাঁকা প্রবন্ধ লিখি না। আমাদের জ্ঞান ভিত্তি তরল গতিবিদ্যা, মেইলার্ড প্রতিক্রিয়া এবং নিষ্কাশন ফলনের শারীরিক সীমা নিয়ে গভীরভাবে আলোচনা করে, আপনাকে 'কীভাবে' এর পিছনের 'কেন' বুঝতে সাহায্য করে।",
      "about.promise.title": "আমাদের প্রতিশ্রুতি",
      "about.promise.p1": "Barista Flow তার মূল সরঞ্জামগুলি স্থায়ীভাবে বিনামূল্যে রাখার প্রতিশ্রুতি দেয়। আমরা একটি চূড়ান্ত, বিভ্রান্তি-মুক্ত ব্যবহারকারীর অভিজ্ঞতা প্রদান করতে প্রতিশ্রুতিবদ্ধ (একটি সাবধানে ডিজাইন করা ডার্ক মোড এবং মসৃণ অ্যানিমেশন সহ), কারণ আমরা জানি যে সেই তিন মিনিটের ফোকাসড ব্রুইংয়ের সময়, একটি খারাপ ইন্টারফেস দ্বারা আপনার বিরক্ত হওয়া উচিত নয়।",
      "about.quote": "নিখুঁত স্বাদ পাওয়ার একমাত্র পথ হলো নির্ভুলতা।",
    },
    "terms": {
      "terms.meta.title": "পরিষেবার শর্তাবলী | Barista Flow",
      "terms.meta.desc": "Barista Flow পরিষেবার শর্তাবলী। ওয়েবসাইট ব্যবহার, মেধা সম্পদ এবং অস্বীকৃতি সংক্রান্ত প্রবিধান।",
      "terms.intro": "Barista Flow ('ওয়েবসাইট')-এ স্বাগতম। এই ওয়েবসাইট দ্বারা প্রদত্ত কোনো সরঞ্জাম এবং সামগ্রী ব্রাউজ, অ্যাক্সেস বা ব্যবহার করার মাধ্যমে, আপনি নিম্নলিখিত পরিষেবার শর্তাবলীর সাথে পুরোপুরি সম্মত এবং তা গ্রহণ করেন। আপনি যদি এই শর্তাবলীর কোনো অংশের সাথে সম্মত না হন, তবে অনুগ্রহ করে এই ওয়েবসাইটটি ব্যবহার করবেন না।",
      "terms.s1.p1": "Barista Flow বিনামূল্যে অনলাইন কফি ব্রুইং টাইমার, প্যারামিটার গণনা সরঞ্জাম এবং কফি বিজ্ঞান সম্পর্কিত জ্ঞানমূলক প্রবন্ধ প্রদান করে। এই ওয়েবসাইটটি ব্যক্তিগত, অ-বাণিজ্যিক রেফারেন্স এবং সহায়তার উদ্দেশ্যে তৈরি।",
      "terms.s2.title": "মেধা সম্পদ (Intellectual Property)",
      "terms.s2.p1": "এই ওয়েবসাইটের সমস্ত সামগ্রী, যার মধ্যে টেক্সট, লোগো, ছবি, চার্ট, অ্যাপ্লিকেশন কোড, ইউআই ডিজাইন এবং আর্কিটেকচার অন্তর্ভুক্ত, তা Barista Flow টিমের সম্পত্তি বা ব্যবহারের জন্য আইনগতভাবে অনুমোদিত।",
      "terms.s2.l1": "আমাদের পূর্বানুমতি ছাড়া, আপনি কোনো বাণিজ্যিক উদ্দেশ্যে এই ওয়েবসাইটের সামগ্রী কপি, সংশোধন, বিতরণ, প্রকাশ, প্রদর্শন বা ব্যবহার করতে পারবেন না।",
      "terms.s2.l2": "আপনি ব্যক্তিগত শেখার উদ্দেশ্যে এই ওয়েবসাইটের লিঙ্ক শেয়ার করতে পারেন (উদাহরণস্বরূপ, আমাদের 'এই রেসিপি শেয়ার করুন' বৈশিষ্ট্য ব্যবহার করে)।",
      "terms.s3.p1": "এই ওয়েবসাইট দ্বারা প্রদত্ত সমস্ত কফি প্যারামিটার, নির্দেশমূলক প্রবন্ধ এবং টাইমিং সরঞ্জামগুলি 'যেমন আছে' ভিত্তিতে প্রদান করা হয়। যদিও আমরা বৈজ্ঞানিক নির্ভুলতার জন্য চেষ্টা করি, কফি ব্রুইং অনেক শারীরিক ভেরিয়েবল দ্বারা প্রভাবিত হয় (যেমন জলের গুণমান, বীজের ধরন, তাপমাত্রা ইত্যাদি)।",
      "terms.s3.l1": "আমরা এই ওয়েবসাইটের সামগ্রীর সম্পূর্ণ নির্ভুলতা, পূর্ণতা বা প্রযোজ্যতার বিষয়ে কোনো স্পষ্ট বা নিহিত ওয়ারেন্টি প্রদান করি না।",
      "terms.s3.l2": "Barista Flow এই ওয়েবসাইটের সরঞ্জামগুলি ব্যবহার বা এই ওয়েবসাইটের তথ্যের উপর নির্ভর করার কারণে সৃষ্ট কোনো প্রত্যক্ষ, পরোক্ষ বা আনুষঙ্গিক ক্ষতির (কফি বীজের ক্ষতি বা সরঞ্জামের ক্ষতি সহ কিন্তু সীমাবদ্ধ নয়) জন্য দায়ী নয়।",
      "terms.s4.title": "ব্যবহারকারীর আচরণ",
      "terms.s4.p1": "এই ওয়েবসাইট ব্যবহার করার সময়, আপনি সমস্ত প্রযোজ্য আইন এবং প্রবিধান মেনে চলতে সম্মত হন এবং আপনার যা করা উচিত নয়:",
      "terms.s4.l1": "এই ওয়েবসাইটটিকে এমন কোনো উপায়ে ব্যবহার করা যা ওয়েবসাইটের সার্ভার বা নেটওয়ার্ককে ওভারলোড, ক্ষতিগ্রস্থ বা বাধাগ্রস্ত করতে পারে (যেমন DDoS আক্রমণ বা দূষিত স্ক্র্যাপিং)।",
      "terms.s4.l2": "ওয়েবসাইটের ব্যাকএন্ড সিস্টেম বা সোর্স কোডে অননুমোদিত অ্যাক্সেস পাওয়ার চেষ্টা করা।",
      "terms.s4.l3": "কোনো বেআইনি বা প্রতারণামূলক কার্যকলাপে জড়িত হতে এই ওয়েবসাইট ব্যবহার করা।",
      "terms.s5.title": "তৃতীয় পক্ষের পরিষেবা এবং বিজ্ঞাপন",
      "terms.s5.p1": "এই ওয়েবসাইটে তৃতীয় পক্ষের ওয়েবসাইটের লিঙ্ক থাকতে পারে বা তৃতীয় পক্ষের বিজ্ঞাপন (যেমন Google AdSense) প্রদর্শিত হতে পারে। এই তৃতীয় পক্ষের ওয়েবসাইটগুলির সামগ্রী এবং গোপনীয়তা নীতিগুলির উপর আমাদের কোনো নিয়ন্ত্রণ নেই। বিজ্ঞাপন বা বহিরাগত লিঙ্কগুলিতে ক্লিক করার কারণে উদ্ভূত যেকোনো ঝুঁকির দায়িত্ব সম্পূর্ণ ব্যবহারকারীর।",
      "terms.s6.title": "সংশোধন এবং সমাপ্তি",
      "terms.s6.p1": "আমরা কোনো পূর্ব বিজ্ঞপ্তি ছাড়াই যেকোনো সময় এই ওয়েবসাইটের পরিষেবাগুলি এবং এই পরিষেবার শর্তাবলী সংশোধন, স্থগিত বা বন্ধ করার অধিকার সংরক্ষণ করি। এই ওয়েবসাইটের আপনার অবিরত ব্যবহার কোনো সংশোধিত শর্তাবলীর প্রতি আপনার সম্মতি গঠন করে।",
    }
  },
  "ar": {
    "about": {
      "about.meta.title": "معلومات عنا | Barista Flow",
      "about.meta.desc": "اكتشف مهمة Barista Flow. نحن مكرسون لرقمنة علوم القهوة وإنشاء أدوات تحضير القهوة المختصة الأكثر احترافية في العالم.",
      "about.title": "معلومات عنا",
      "about.intro": "في عالم القهوة المختصة، المتغيرات الدقيقة تحدد النكهة النهائية. وُلدت Barista Flow لحل مشكلة يواجهها كل محب للقهوة: 'كيف نجعل كل عملية تحضير مستقرة، دقيقة، ومبنية على أسس علمية؟'",
      "about.vision.title": "رؤيتنا",
      "about.vision.p1": "نحن مجموعة من المطورين والباريستا الشغوفين بالقهوة. نعتقد أن فنجان القهوة الجيد لا ينبغي أن يعتمد فقط على 'الشعور' أو 'الحظ'. يمكن قياس درجة حرارة الماء، ونسبة التحضير، وحجم الطحن، وديناميكيات السوائل الحاسمة (إيقاع الصب) والتحكم فيها جميعًا باستخدام البيانات العلمية.",
      "about.vision.p2": "هي بناء منصة أدوات تحضير القهوة الأكثر احترافية وسهولة في الاستخدام في العالم، مما يتيح للجميع، من المبتدئين في التقطير إلى الباريستا المتمرسين، العثور على إجابات لرفع جودة الاستخلاص لديهم.",
      "about.offer.title": "ما نقدمه",
      "about.offer.l1.title": "مؤقت تفاعلي من 3 مراحل",
      "about.offer.l1": "احسب على الفور التوقيت الأمثل للصب وأهداف حجم الماء للترطيب، والاستخلاص الرئيسي، والمرحلة النهائية بناءً على نوع حبوب القهوة ونسبة التحضير.",
      "about.offer.l2.title": "حفظ الوصفات ومشاركتها",
      "about.offer.l2": "يتيح لك حفظ كل وصفة ناجحة ومشاركة فلسفتك في التحضير مع عشاق القهوة في جميع أنحاء العالم عبر رابط مخصص.",
      "about.offer.l3.title": "قاعدة معرفية متعمقة",
      "about.offer.l3": "نحن لا نكتب مقالات فارغة. تغوص قاعدة المعرفة لدينا عميقًا في ديناميكيات السوائل، وتفاعل مايار، والحدود الفيزيائية لعائد الاستخلاص، مما يساعدك على فهم 'السبب' وراء 'الكيفية'.",
      "about.promise.title": "وعدنا",
      "about.promise.p1": "تعد Barista Flow بالحفاظ على أدواتها الأساسية مجانية بشكل دائم. نحن ملتزمون بتوفير تجربة مستخدم مثالية وخالية من التشتيت (بما في ذلك الوضع الليلي المصمم بعناية والرسوم المتحركة السلسة)، لأننا نعلم أنه خلال دقائق التحضير الثلاث المركزة، لا ينبغي أن تزعجك واجهة سيئة.",
      "about.quote": "الدقة هي الطريق الوحيد إلى النكهة المطلقة.",
    },
    "terms": {
      "terms.meta.title": "شروط الخدمة | Barista Flow",
      "terms.meta.desc": "شروط خدمة Barista Flow. اللوائح الخاصة باستخدام الموقع، والملكية الفكرية، وإخلاء المسؤولية.",
      "terms.intro": "مرحبًا بك في Barista Flow ('الموقع'). من خلال تصفح أو الوصول إلى أو استخدام أي أدوات ومحتوى يقدمه هذا الموقع، فإنك توافق تمامًا وتقبل شروط الخدمة التالية. إذا كنت لا توافق على أي جزء من هذه الشروط، يرجى عدم استخدام هذا الموقع.",
      "terms.s1.p1": "توفر Barista Flow مؤقتات مجانية عبر الإنترنت لتحضير القهوة، وأدوات لحساب المعلمات، ومقالات معرفية متعلقة بعلوم القهوة. هذا الموقع مخصص للرجوع إليه وللمساعدة الشخصية غير التجارية.",
      "terms.s2.title": "الملكية الفكرية",
      "terms.s2.p1": "جميع المحتويات الموجودة على هذا الموقع، بما في ذلك على سبيل المثال لا الحصر، النصوص والشعارات والصور والرسوم البيانية وكود التطبيق وتصميم واجهة المستخدم والهندسة المعمارية، هي ملك لفريق Barista Flow أو تم التصريح باستخدامها قانونيًا.",
      "terms.s2.l1": "بدون إذن كتابي مسبق منا، لا يجوز لك نسخ أو تعديل أو توزيع أو نشر أو عرض أو استخدام محتوى هذا الموقع لأي أغراض تجارية.",
      "terms.s2.l2": "يمكنك مشاركة الروابط إلى هذا الموقع لأغراض التعلم الشخصي (على سبيل المثال، باستخدام ميزة 'مشاركة هذه الوصفة').",
      "terms.s3.p1": "يتم توفير جميع معلمات القهوة والمقالات التعليمية وأدوات التوقيت التي يوفرها هذا الموقع 'كما هي'. في حين أننا نسعى جاهدين لتحقيق الدقة العلمية، فإن تحضير القهوة يتأثر بالعديد من المتغيرات الفيزيائية (مثل جودة الماء، نوع الحبوب، درجة الحرارة، إلخ).",
      "terms.s3.l1": "نحن لا نقدم أي ضمانات صريحة أو ضمنية فيما يتعلق بالدقة المطلقة أو الاكتمال أو قابلية تطبيق المحتوى على هذا الموقع.",
      "terms.s3.l2": "Barista Flow ليست مسؤولة عن أي خسائر مباشرة أو غير مباشرة أو عرضية (بما في ذلك على سبيل المثال لا الحصر، فقدان حبوب القهوة أو تلف المعدات) الناتجة عن استخدام الأدوات الموجودة على هذا الموقع أو الاعتماد على المعلومات الموجودة على هذا الموقع.",
      "terms.s4.title": "سلوك المستخدم",
      "terms.s4.p1": "عند استخدام هذا الموقع، فإنك توافق على الامتثال لجميع القوانين واللوائح المعمول بها، ويجب عليك ألا:",
      "terms.s4.l1": "تستخدم هذا الموقع بأي طريقة يمكن أن تتسبب في زيادة تحميل خادم الموقع أو شبكته، أو إتلافهما، أو مقاطعتهما (مثل هجمات DDoS أو الكشط الضار).",
      "terms.s4.l2": "تحاول الحصول على وصول غير مصرح به إلى نظام الواجهة الخلفية أو الكود المصدري للموقع.",
      "terms.s4.l3": "تستخدم هذا الموقع للمشاركة في أي أنشطة غير قانونية أو احتيالية.",
      "terms.s5.title": "خدمات وإعلانات الطرف الثالث",
      "terms.s5.p1": "قد يحتوي هذا الموقع على روابط لمواقع ويب تابعة لجهات خارجية أو يعرض إعلانات تابعة لجهات خارجية (مثل Google AdSense). ليس لدينا أي سيطرة على محتوى وسياسات الخصوصية الخاصة بمواقع الجهات الخارجية هذه. أي مخاطر تنشأ عن النقر على الإعلانات أو الروابط الخارجية هي مسؤولية المستخدم وحده.",
      "terms.s6.title": "التعديل والإنهاء",
      "terms.s6.p1": "نحتفظ بالحق في تعديل أو تعليق أو إنهاء خدمات هذا الموقع وشروط الخدمة هذه في أي وقت دون إشعار مسبق. استمرارك في استخدام هذا الموقع يشكل قبولك لأي شروط معدلة.",
    }
  },
  "ur": {
    "about": {
      "about.meta.title": "ہمارے بارے میں | Barista Flow",
      "about.meta.desc": "Barista Flow کے مشن کو دریافت کریں۔ ہم کافی سائنس کو ڈیجیٹائز کرنے اور دنیا کے سب سے زیادہ پیشہ ورانہ کافی بریونگ ٹولز بنانے کے لیے وقف ہیں۔",
      "about.title": "ہمارے بارے میں",
      "about.intro": "اسپیشلٹی کافی کی دنیا میں، معمولی تغیرات حتمی ذائقے کا تعین کرتے ہیں۔ Barista Flow ہر کافی پریمی کو درپیش اس مسئلے کو حل کرنے کے لیے پیدا ہوا تھا: 'ہم ہر برو کو مستحکم، درست اور سائنسی بنیادوں پر کیسے بنائیں؟'",
      "about.vision.title": "ہمارا وژن",
      "about.vision.p1": "ہم ڈیولپرز اور باریستاس کا ایک گروپ ہیں جو کافی کا شوق رکھتے ہیں۔ ہمارا ماننا ہے کہ کافی کا ایک اچھا کپ صرف 'احساس' یا 'قسمت' پر انحصار نہیں کرنا چاہیے۔ پانی کا درجہ حرارت، برو تناسب، پیسنے کا سائز، اور انتہائی اہم سیال حرکیات (ڈالنے کی تال) کو سائنسی ڈیٹا کا استعمال کرتے ہوئے مقدار کا تعین اور کنٹرول کیا جا سکتا ہے۔",
      "about.vision.p2": "دنیا کا سب سے زیادہ پیشہ ورانہ اور استعمال میں آسان کافی بریونگ ٹول پلیٹ فارم بنانا ہے، جس سے پور-اوور مبتدیوں سے لے کر تجربہ کار باریستاس تک ہر ایک کو اپنی نکالنے کے معیار کو بلند کرنے کے جوابات مل سکیں۔",
      "about.offer.title": "ہم کیا پیش کرتے ہیں",
      "about.offer.l1.title": "انٹرایکٹو 3-اسٹیج ٹائمر",
      "about.offer.l1": "اپنے بین کی قسم اور برو تناسب کی بنیاد پر بلوم، مرکزی نکالنے، اور حتمی مرحلے کے لیے زیادہ سے زیادہ ڈالنے کے وقت اور پانی کے حجم کے اہداف کا فوری حساب لگائیں۔",
      "about.offer.l2.title": "ترکیب کو محفوظ کرنا اور شیئر کرنا",
      "about.offer.l2": "آپ کو ہر کامیاب ترکیب کو محفوظ کرنے اور ایک مخصوص لنک کے ذریعے دنیا بھر میں کافی کے شوقین افراد کے ساتھ اپنے بریونگ فلسفے کو شیئر کرنے کی اجازت دیتا ہے۔",
      "about.offer.l3.title": "گہرا نالج بیس",
      "about.offer.l3": "ہم خالی مضامین نہیں لکھتے ہیں۔ ہمارا علمی مرکز سیال کی حرکیات، میلارڈ کے رد عمل، اور نکالنے کی پیداوار کی جسمانی حدود میں گہرائی میں غوطہ لگاتا ہے، جس سے آپ کو 'کیسے' کے پیچھے 'کیوں' کو سمجھنے میں مدد ملتی ہے۔",
      "about.promise.title": "ہمارا وعدہ",
      "about.promise.p1": "Barista Flow اپنے بنیادی ٹولز کو مستقل طور پر مفت رکھنے کا وعدہ کرتا ہے۔ ہم ایک حتمی، خلفشار سے پاک صارف کا تجربہ (جس میں احتیاط سے ڈیزائن کیا گیا ڈارک موڈ اور ہموار اینیمیشن شامل ہیں) فراہم کرنے کے لیے پرعزم ہیں، کیونکہ ہم جانتے ہیں کہ ان تین منٹوں کی توجہ مرکوز کرنے کے دوران، آپ کو خراب انٹرفیس سے پریشان نہیں ہونا چاہیے۔",
      "about.quote": "درستگی حتمی ذائقے کا واحد راستہ ہے۔",
    },
    "terms": {
      "terms.meta.title": "سروس کی شرائط | Barista Flow",
      "terms.meta.desc": "Barista Flow سروس کی شرائط۔ ویب سائٹ کے استعمال، دانشورانہ املاک، اور دستبرداری سے متعلق ضوابط۔",
      "terms.intro": "Barista Flow ('ویب سائٹ') میں خوش آمدید۔ اس ویب سائٹ کے ذریعہ فراہم کردہ کسی بھی ٹولز اور مواد کو براؤز کرنے، ان تک رسائی حاصل کرنے یا ان کا استعمال کرنے سے، آپ درج ذیل سروس کی شرائط سے پوری طرح متفق اور قبول کرتے ہیں۔ اگر آپ ان شرائط کے کسی بھی حصے سے متفق نہیں ہیں، تو براہ کرم اس ویب سائٹ کا استعمال نہ کریں۔",
      "terms.s1.p1": "Barista Flow کافی کی سائنس سے متعلق مفت آن لائن کافی بریونگ ٹائمر، پیرامیٹر کیلکولیشن ٹولز، اور علمی مضامین فراہم کرتا ہے۔ یہ ویب سائٹ ذاتی، غیر تجارتی حوالہ اور مدد کے لیے ہے۔",
      "terms.s2.title": "دانشورانہ املاک",
      "terms.s2.p1": "اس ویب سائٹ پر موجود تمام مواد، بشمول لیکن ان تک محدود نہیں، متن، لوگو، تصاویر، چارٹس، ایپلیکیشن کوڈ، UI ڈیزائن، اور فن تعمیر، Barista Flow ٹیم کی ملکیت ہیں یا انہیں قانونی طور پر استعمال کے لیے اختیار دیا گیا ہے۔",
      "terms.s2.l1": "ہماری پیشگی تحریری اجازت کے بغیر، آپ تجارتی مقاصد کے لیے اس ویب سائٹ کے مواد کو کاپی، ترمیم، تقسیم، شائع، ڈسپلے یا استعمال نہیں کر سکتے۔",
      "terms.s2.l2": "آپ ذاتی سیکھنے کے مقاصد کے لیے اس ویب سائٹ کے لنکس شیئر کر سکتے ہیں (مثال کے طور پر، ہماری 'اس ترکیب کو شیئر کریں' خصوصیت کا استعمال کرتے ہوئے)۔",
      "terms.s3.p1": "اس ویب سائٹ کی طرف سے فراہم کردہ تمام کافی پیرامیٹرز، تدریسی مضامین، اور ٹائمنگ ٹولز 'جیسا ہے' فراہم کیے گئے ہیں۔ اگرچہ ہم سائنسی درستگی کے لیے کوشش کرتے ہیں، کافی بنانے کا عمل بہت سے جسمانی تغیرات (جیسے پانی کا معیار، بین کی قسم، درجہ حرارت، وغیرہ) سے متاثر ہوتا ہے۔",
      "terms.s3.l1": "ہم اس ویب سائٹ پر موجود مواد کی مطلق درستگی، مکملیت، یا اطلاق کے حوالے سے کوئی واضح یا مضمر وارنٹی نہیں دیتے ہیں۔",
      "terms.s3.l2": "Barista Flow کسی بھی براہ راست، بالواسطہ، یا حادثاتی نقصانات (بشمول لیکن ان تک محدود نہیں، کافی کی پھلیاں ضائع ہونا یا آلات کو پہنچنے والے نقصان) کا ذمہ دار نہیں ہے جو اس ویب سائٹ پر موجود ٹولز کے استعمال یا اس ویب سائٹ پر موجود معلومات پر انحصار کرنے کی وجہ سے ہو۔",
      "terms.s4.title": "صارف کا برتاؤ",
      "terms.s4.p1": "اس ویب سائٹ کا استعمال کرتے وقت، آپ تمام قابل اطلاق قوانین اور ضوابط کی تعمیل کرنے سے اتفاق کرتے ہیں، اور آپ کو ایسا نہیں کرنا چاہیے:",
      "terms.s4.l1": "اس ویب سائٹ کو کسی بھی طرح سے استعمال کریں جس سے ویب سائٹ کا سرور یا نیٹ ورک اوورلوڈ، خراب، یا روکا جا سکے (جیسے DDoS حملے یا بدنیتی پر مبنی سکریپنگ)۔",
      "terms.s4.l2": "ویب سائٹ کے بیک اینڈ سسٹم یا سورس کوڈ تک غیر مجاز رسائی حاصل کرنے کی کوشش کریں۔",
      "terms.s4.l3": "کسی بھی غیر قانونی یا دھوکہ دہی کی سرگرمیوں میں ملوث ہونے کے لیے اس ویب سائٹ کا استعمال کریں۔",
      "terms.s5.title": "تھرڈ پارٹی سروسز اور اشتہارات",
      "terms.s5.p1": "اس ویب سائٹ میں فریق ثالث کی ویب سائٹس کے لنکس ہو سکتے ہیں یا فریق ثالث کے اشتہارات (جیسے Google AdSense) دکھا سکتے ہیں۔ ان فریق ثالث کی ویب سائٹس کے مواد اور رازداری کی پالیسیوں پر ہمارا کوئی کنٹرول نہیں ہے۔ اشتہارات یا بیرونی روابط پر کلک کرنے سے پیدا ہونے والا کوئی بھی خطرہ صارف کی واحد ذمہ داری ہے۔",
      "terms.s6.title": "ترمیم اور برطرفی",
      "terms.s6.p1": "ہم بغیر پیشگی اطلاع کے کسی بھی وقت اس ویب سائٹ کی خدمات اور سروس کی ان شرائط کو تبدیل کرنے، معطل کرنے یا ختم کرنے کا حق محفوظ رکھتے ہیں۔ اس ویب سائٹ کا آپ کا مسلسل استعمال کسی بھی ترمیم شدہ شرائط کی آپ کی منظوری کو تشکیل دیتا ہے۔",
    }
  }
}

for lang, lang_data in translations.items():
    injected_str = ''
    for section_key, section_dict in lang_data.items():
        for k, v in section_dict.items():
            escaped_v = v.replace("'", "\\'")
            injected_str += f"    '{k}': '{escaped_v}',\n"
    
    target1 = f'"{lang}": {{\n'
    target2 = f"'{lang}': {{\n"
    
    if target1 in text:
        text = text.replace(target1, target1 + injected_str)
    elif target2 in text:
        text = text.replace(target2, target2 + injected_str)

with open(ui_ts_path, 'w') as f:
    f.write(text)

